import sys, unreal
sys.path.append(r'C:\Program Files\Epic Games\UE_5.8\Engine\Plugins\Experimental\Toolsets\EditorToolset\Content\Python')
from editor_toolset.toolsets.blueprint import BlueprintTools as B
from editor_toolset.toolsets.actor import ActorTools as A
PATH='/Game/Weapons'
def blueprint(name):
    return unreal.load_asset(PATH+'/'+name) if unreal.EditorAssetLibrary.does_asset_exist(PATH+'/'+name) else B.create(PATH,name,unreal.Actor.static_class())
connect=blueprint('BP_Rifle_Connect')
interact=blueprint('BP_Rifle_Interact')
for bp in (connect,interact):
    g=unreal.BlueprintEditorLibrary.find_event_graph(bp)
    for old in B.find_nodes(g): B.delete_node(old)
    cdo=B.get_default_object(bp)
    tick=cdo.get_editor_property('primary_actor_tick')
    tick.set_editor_property('start_with_tick_enabled',False)
    cdo.set_editor_property('primary_actor_tick',tick)
    components=A.get_components(cdo,unreal.StaticMeshComponent.static_class())
    mesh=components[0] if components else A.add_component(bp,unreal.StaticMeshComponent.static_class(),'WeaponMesh')
    mesh.set_editor_property('static_mesh',unreal.load_asset('/Engine/BasicShapes/Cube'))
    mesh.set_editor_property('relative_scale3d',unreal.Vector(0.65,0.10,0.16))
    mesh.set_editor_property('mobility',unreal.ComponentMobility.MOVABLE)
    mesh.set_collision_profile_name('BlockAllDynamic' if bp==interact else 'NoCollision')
    B.compile_blueprint(bp)
g=unreal.BlueprintEditorLibrary.find_event_graph(interact)
B.get_default_object(interact).set_editor_property('auto_receive_input',unreal.AutoReceiveInput.PLAYER0)
types=B.find_node_types(g,'')
nodes={}
def node(key,type_id):
    if '|' not in type_id:
        matches=[t for t in types if t.split('|')[-1]==type_id]
        assert matches,(key,type_id)
        type_id=matches[0]
    n=B.create_node(g,type_id,unreal.IntPoint(len(nodes)*240,0)); nodes[key]=n
    unreal.log_warning('WPIN '+key+' '+str([str(p.get_pin_name()) for p in n.list_all_pins()]))
    return n
for key,typ in [('key','Input|KeyboardEvents|E'),('player','GetPlayerCharacter'),('camera','GetPlayerCameraManager'),('loc','GetCameraLocation'),('rot','GetCameraRotation'),('forward','Math|Vector|GetForwardVector'),('mul','Utilities|Operators|Multiply'),('add','Utilities|Operators|Add'),('trace','LineTraceByChannel'),('hit','BreakHitResult'),('self','Getareferencetoself'),('equal','Utilities|Operators|Equal(==)'),('distance','GetDistanceTo'),('near','Utilities|Operators|LessEqual(<=)'),('branch','Utilities|FlowControl|Branch'),('spawn','SpawnActorfromClass'),('mesh','Class|Character|GetMesh'),('attach','AttachActorToComponent'),('destroy','DestroyActor')]: node(key,typ)
def pin(key,name):
    return next(p for p in nodes[key].list_all_pins() if str(p.get_pin_name()).lower()==name.lower())
def wire(a,ap,b,bp):
    assert pin(a,ap).try_create_connection(pin(b,bp)),(a,ap,b,bp)
def val(key,p,value):
    B.set_pin_value(B._pin_to_id(pin(key,p)),value)
node('ignore','Utilities|Array|MakeArray')
node('nearbranch','Utilities|FlowControl|Branch')
node('attached','Utilities|FlowControl|Branch')
node('validspawn','Utilities|IsValid')
node('socket','DoesSocketExist')
node('socketbranch','Utilities|FlowControl|Branch')
node('transform','MakeTransform')
nodes['key'].set_editor_property('consume_input',False)
wire('camera','ReturnValue','loc','self')
wire('camera','ReturnValue','rot','self')
wire('rot','ReturnValue','forward','InRot')
wire('forward','ReturnValue','mul','A')
val('mul','B','2000,2000,2000')
wire('loc','ReturnValue','add','A')
wire('mul','ReturnValue','add','B')
wire('loc','ReturnValue','trace','Start')
wire('add','ReturnValue','trace','End')
wire('player','ReturnValue','ignore','[0]')
wire('ignore','Array','trace','ActorsToIgnore')
val('trace','bIgnoreSelf','false')
val('trace','TraceChannel','TraceTypeQuery1')
val('trace','DrawDebugType','None')
wire('key','Pressed','trace','execute')
wire('trace','OutHit','hit','Hit')
wire('hit','HitActor','equal','A')
wire('self','self','equal','B')
wire('trace','then','branch','execute')
wire('equal','ReturnValue','branch','Condition')
wire('player','ReturnValue','distance','OtherActor')
wire('distance','ReturnValue','near','A')
val('near','B','200.0')
wire('branch','then','nearbranch','execute')
wire('near','ReturnValue','nearbranch','Condition')
wire('player','ReturnValue','mesh','self')
wire('mesh','Mesh','socket','self')
val('socket','InSocketName','hand_r')
wire('nearbranch','then','socketbranch','execute')
wire('socket','ReturnValue','socketbranch','Condition')
wire('socketbranch','then','spawn','execute')
val('spawn','Class',connect.generated_class().get_path_name())
val('spawn','CollisionHandlingOverride','AlwaysSpawn')
wire('transform','ReturnValue','spawn','SpawnTransform')
wire('player','ReturnValue','spawn','Owner')
wire('spawn','then','validspawn','exec')
wire('spawn','ReturnValue','validspawn','InputObject')
wire('validspawn','Is Valid','attach','execute')
wire('spawn','ReturnValue','attach','self')
wire('mesh','Mesh','attach','Parent')
val('attach','SocketName','hand_r')
val('attach','LocationRule','SnapToTarget')
val('attach','RotationRule','SnapToTarget')
val('attach','ScaleRule','KeepWorld')
val('attach','bWeldSimulatedBodies','false')
wire('attach','then','attached','execute')
wire('attach','ReturnValue','attached','Condition')
wire('attached','then','destroy','execute')
for bp in (connect,interact):
    bp.modify()
    B.compile_blueprint(bp,True)
    assert unreal.EditorAssetLibrary.save_loaded_asset(bp)
    unreal.log_warning('WEAPON_SAVED '+bp.get_path_name())
unreal.log_warning('WEAPON_DSL '+B.read_graph_dsl(g))
